### ISSUE TITLE
Accessing config.yaml parameters

### ISSUE THREAD

**Issue by baturorkun** [nficano/python-lambda#468]
I want to access config.yaml parameters. For example "aws_access_key_id" or "description" or "timeout"  etc.. I could not find any object for this.

**Comment by ninurtalabs** [comment]
Define your variables preferably under `environment_variables` e.g.
In `config.yml`
```yaml
environment_variables:
  timeout: 5
  key: xxx
```

Then in your Python file
```python
import os
timeout = os.environ.get("timeout")
```
